### ISSUE TITLE
Do we actually need this?

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHubMe.github.io#1]
B/c of planhub.me? aka what would this do

**Comment by thatoddmailbox** [comment]
@medensqui I had to make it so GitHub would allow project pages like the API docs.

**Comment by willbarkoff** [comment]
@thatoddmailbox Can I have write access to all of the PlanHub.Me Projects?

**Comment by thatoddmailbox** [comment]
@nywillb I think I did that, though I might have forgotten a project...

(let me know if it still isn't working)
